refactor(auth): rollback to use application password
buddytrading/bfx-hf-server pull request #2
Opened 2023-02-13 10:14 UTC by duylddev

2023-02-14 02:48 UTC, jengjeng requested changes

2023-02-14 02:48 UTC, jengjeng commented on lib/ws_servers/api/handlers/strategy/live_strategy_execution_start.js
> +  // const { apiKey, apiSecret } = ws.getCredentials()
can you comment on why this code is not used?

2023-02-14 02:48 UTC, jengjeng commented on package.json
> +    "bfx-api-node-core": "github:buddytrading/bfx-api-node-core",
add commit tag please

2023-02-14 02:48 UTC, jengjeng commented on package.json
> +    "bfx-hf-strategy-exec": "github:buddytrading/bfx-hf-strategy-exec",
this too

2023-02-14 06:46 UTC, duylddev commented on package.json
> +    "bfx-api-node-core": "github:buddytrading/bfx-api-node-core",
if I add the commit tag here that means when I push code to `bfx-api-node-core` I have to go back here to change the commit tag, and then we will find which library use `bfx-hf-server` to change commit tag, and so on. The point is we don't know which use `bfx-api-node-core` and `bfx-hf-server` and take time to update 1 library

I see Bitfinex ignore `package-lock.json` file in `.gitignore` => when we left commit tag blank, we always get the latest version of `bfx-api-node-core`

Summary:
Add commit tag pros: to know which current version is, 
Add commit tag cons: manual update package.json of all relatives library

remove commit tag pros: always get the latest version at first install
remove commit tag cons: npm install without package-lock.json to get the latest version

what is your call?

2023-02-14 07:13 UTC, jengjeng commented on package.json
> +    "bfx-api-node-core": "github:buddytrading/bfx-api-node-core",
If we remove `package-lock.json`, other dependencies will affect too (not only our custom repo).
then I would prefer to add a commit tag.
but can you list for me which repo using `bfx-api-node-core` and `bfx-hf-strategy-exec` ?

2023-02-14 07:23 UTC, duylddev commented on package.json
> +    "bfx-api-node-core": "github:buddytrading/bfx-api-node-core",
bfx-api-node-core

1. bfx-hf-strategy-exec
2. bfx-hf-server
3.

2023-02-14 07:28 UTC, duylddev commented on package.json
> +    "bfx-api-node-core": "github:buddytrading/bfx-api-node-core",
They use in many library, here I only list which we're using:

**bfx-api-node-core**

1. bfx-hf-strategy-exec
2. bfx-hf-server
3. bfx-hf-strategy

**bfx-hf-strategy-exec**
1. bfx-hf-server

it works like a loop, we update bfx-api-node-core => update bfx-hf-strategy-exec => update bfx-hf-server => buddytrading/packages/bfx-hf-ui

2023-02-14 11:32 UTC, jengjeng commented on package.json
> +    "bfx-api-node-core": "github:buddytrading/bfx-api-node-core",
let's do adding commit tag for now.
because in production we will use `npm ci` and we can not always install from the latest commit on each repo.

2023-02-14 11:36 UTC, duylddev commented on package.json
> +    "bfx-api-node-core": "github:buddytrading/bfx-api-node-core",
oke, I'll update it now

2023-02-15 09:47 UTC, jengjeng requested changes

2023-02-15 09:47 UTC, jengjeng commented on .gitignore
> -/data
this`/data` should not be ignored

2023-02-15 09:47 UTC, jengjeng commented on package.json
> +    "bfx-api-node-core": "github:buddytrading/bfx-api-node-core#78bf873ff58f7b417c52a104bf2a0060fbecf00b",
only short has is enough

2023-02-15 09:51 UTC, jengjeng approved these changes

2023-02-15 09:51 UTC, merged